### PR TITLE
refactor: Doc site and feat : responsive

### PR DESCRIPTION
**Pull request by mikesch803**
refactor the previous code,
added media queries

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
LGTM

**Review by ParthParolekar — APPROVED** [review]
Looks good to me!

**Review by ApurvaSawant11 — CHANGES_REQUESTED** [review]
Everything looks great!! Just a few suggestions.
1. Add a floating button -> "Back to top".
2. For smaller screens also, make a fixed component bar so that the user can move to the needed component easily.

**Comment by mikesch803** [comment]
> Everything looks great!! Just a few suggestions.
> 
> 1. Add a floating button -> "Back to top".
> 2. For smaller screens also, make a fixed component bar so that the user can move to the needed component easily.

**Comment by mikesch803** [comment]
> Everything looks great!! Just a few suggestions.
> 
> 1. Add a floating button -> "Back to top".
> 2. For smaller screens also, make a fixed component bar so that the user can move to the needed component easily.

I added the floating btn and for the small screen, I do it later(remove media queries)

**Pull request merged**
